### ISSUE TITLE
Support for VSCode

### ISSUE THREAD

**Issue by sidletsky** [gaplo917/GapStyle#10]
Hi!

I love your color scheme. 

Is it possible to get this style for VSCode?

**Comment by gaplo917** [comment]
@sidletsky Thank you for your appreciation. 

Recently built a Web Version of GapStyle (Prism.js Theme) and will be publish very soon. 

<img width="966" alt="Screenshot 2020-03-01 at 19 44 18" src="https://user-images.githubusercontent.com/5468398/75625034-15424080-5bf5-11ea-8431-3487287e6a03.png">

The next step will be VSCode!

**Comment by sidletsky** [comment]
Is there anything I can help with? I am very new to VS Code, but was an Intelijj user for years.

**Comment by RichardFido** [comment]
also like this color scheme. i used it for a long time in clion. but use vscode instead recently. Can you support c++ language in VS Code?

**Comment by gaplo917** [comment]
@RichardFido Have started to learn about VS Theme implementation last week and successfully completed a barebone (The hardest part) . 

I think the first usable draft will be released before April. 🎉

**Comment by gaplo917** [comment]
@sidletsky @RichardFido I am thrill to announce GapStyle VS is available in VSCode Marketplace.
