### ISSUE TITLE
colorizes whitespace

### ISSUE THREAD

**Issue by Raynos** [gaplo917/GapStyle#19]
Thanks for this extension, the syntax highlighting is very semantically meaningful.

It looks like this extensions colorizes whitespace when the option

```json
    "editor.renderWhitespace": "all",
```

is set.

![image](https://user-images.githubusercontent.com/479538/81691113-97a07980-945c-11ea-9ade-304b6ec45e39.png)

The variable names that i am destructuring across multiple lines in this destructuring block are being printed with whitespace.

![image](https://user-images.githubusercontent.com/479538/81691195-b999fc00-945c-11ea-96c0-3e35bae7f012.png)

Function calls and variables have the same behavior, its not always the same color

![image](https://user-images.githubusercontent.com/479538/81691263-d2a2ad00-945c-11ea-9328-22fa0242b04a.png)

**Comment by Raynos** [comment]
I found an even worse edge cases where its colorizing a comment expression

![image](https://user-images.githubusercontent.com/479538/81691333-eea64e80-945c-11ea-9040-0bf32c3df899.png)

**Comment by Raynos** [comment]
This was a completely unrelated extension -.-

https://marketplace.visualstudio.com/items?itemName=aaaaash.ts-semantic-highlighting

I turned of this extension and the colorized whitespace dissappeared.

Apologies.

**Comment by gaplo917** [comment]
@Raynos Interesting, Thanks for your sharing and responsible actions!
