### ISSUE TITLE
"Identifier under caret" [IntelliJ setting] should have a background

### ISSUE THREAD

**Issue by Appyx** [gaplo917/GapStyle#29]
Since underscored words are hard to identify across a whole "page" of code, there should be a background set.
This wold boost productivity because you instantly know where the object is used.

I'm currently using #676767 as a background color for "Identifier under caret" and "Identifier under caret (write)".
I think this should be a default setting. Not sure about the color and distinction between read and write though.

**Comment by gaplo917** [comment]
@Appyx Thank you for the suggestion. Would you mind share some preview on this suggestion?

**Comment by Appyx** [comment]
@gaplo917 Sure. I can't share complicated code right now but here you go:
<img width="848" alt="image" src="https://user-images.githubusercontent.com/18675385/121786940-44e74300-cbc3-11eb-8320-f56a54cec551.png">

In this example, I instantly know where my variable `power` is used. So I can follow the code much better.

**Comment by gaplo917** [comment]
GapStyleVS do have this implementation but intellij provided more powerful features that can identify the write part.

After a hour of A/B testing on picking the color of identifier under caret(write) part, I am gonna to implement in 4.0 with the following settings.

| Properties | Value |
| --- | --- |
| identifier under caret(write) | Background `#154152`, Effect `#80848D` Bordered|
| identifier under caret | Background `#47484E`, Effect `#80848D` Bordered|

![Screenshot 2021-06-13 at 12 29 58 PM](https://user-images.githubusercontent.com/5468398/121795437-67b93c00-cc43-11eb-9e69-0f41b905c70d.png)

See if this implementation can match your expectation 😄 Thanks for raising out this improvement.

**Comment by Appyx** [comment]
@gaplo917 Wow. This is perfect!
