### ISSUE TITLE
PyCharm: print is printed in pastel blue

### ISSUE THREAD

**Issue by SirStephanikus** [gaplo917/GapStyle#3]
Keywords like print are not in the typicall pink instead in a pastel blue. PyCharm is installed new and uptodate. Also the color menu states that print should be pink...but it isn't ?!?!

**Comment by gaplo917** [comment]
@SirStephanikus  Hi, maybe some color inheritance bug. Could you please try to uninstall and install

Expected color should be preview in here

![](https://cdn.rawgit.com/gaplo917/GapStyle/master/preview/python.png)

**Comment by SirStephanikus** [comment]
I already did. Once on my main workstation and on a laptop...either with the stabler or the EAP version...same results.

Your picture above is also in my settions but the color is different once I edit a real python file

**Comment by gaplo917** [comment]
Thank you for reporting. As I seldom touch python development so the "syntax color judgement" is mainly based on what intellij provided in the nutshell.

Could you please provide a snippet for your case to reproduce the issue 💪🏻.

No Problem when using scratch
<img width="156" alt="screen shot 2018-09-18 at 00 56 28" src="https://user-images.githubusercontent.com/5468398/45637692-b7dc3180-badd-11e8-85c3-adba9195da83.png">

**Comment by SirStephanikus** [comment]
Doesn't matter if I use a scratch file or not. What I figured out is, in the settings menu the print() is pink and is marked as a keyword...len() it's marked as a built-in name...when I change its color to that light-green than also print() in a python file gets light-green than...

I use PyCharm 2018.2.3

**Comment by gaplo917** [comment]
Good to know, I will update the built-in name color to light-green 👍🏻

**Comment by gaplo917** [comment]
https://github.com/gaplo917/GapStyle/issues/4
