### ISSUE TITLE
[Intellij] Identifier Under Caret extremely hard to see

### ISSUE THREAD

**Issue by JamesYeoman** [gaplo917/GapStyle#32]
When the caret is on a keyword, Intellij is meant to highlight each other occurrence of the keyword. The feature is called Identifier Under Caret.

Gapstyle sets this to underline, and I found it's extremely hard to see the underline. To the point where just changing it from outline to bordered made it significantly easier to see. It's still by no means a perfect solution (a proper highlight would be preferred). I've got a couple of screenshots.

The first is gapstyle's default
![image](https://user-images.githubusercontent.com/21042602/137702270-9a3dd3af-15e2-40b6-940c-74ac1e02020b.png)

The second is with the underscore changed to border
![image](https://user-images.githubusercontent.com/21042602/137702144-e5ce1417-c19e-41a4-a64b-8836f9c6d663.png)

As you can see, the underscore blends in with the character, while the border stands out a bit more. Compared to a highlight, it's still illegible, but when trying to configure the background colour to be a highlight, I just couldn't get the colours to look right. So for now, I'll have to settle with a border.

I should note that this is limited to Intellij. VSCode highlighting works fine.

**Comment by kenlee0305** [comment]
There is a proposal from Gap on closed issue - "Identifier under caret" [IntelliJ setting] should have a background.

**Comment by gaplo917** [comment]
@JamesYeoman Thank you for contributing for GapStyle! 

Like @kenlee0305  mentioned, please add the following changes https://github.com/gaplo917/GapStyle/issues/29 by **yourself** 

This changes will be applied to GapStyle 4.0 (WIP)
