### ISSUE TITLE
[Documentation] Vscode setup config is not correct on VS marketplace

### ISSUE THREAD

**Issue by stanley0010** [gaplo917/GapStyle#39]
This is my first time using a semantic highlighting theme:) Thanks @gaplo917 it was amazing.

Though I noticed the config on [VS marketplace](https://marketplace.visualstudio.com/items?itemName=gaplo917.gapstylevs) does not work for me.
<img width="745" alt="image" src="https://user-images.githubusercontent.com/25721992/152630999-2ff197f6-e348-4f55-a83c-ff7f29476311.png">

And in my settings.json, the second line is not recognised by the vscode. (Not sure if this is only a problem for me)
<img width="514" alt="Screenshot 2022-02-05 at 2 11 57 PM" src="https://user-images.githubusercontent.com/25721992/152630981-6c7dbe09-cd7e-4343-a678-148ee39ae42d.png">

So in all, I think the config should be `editor.semanticHighlighting.enabled": true`, which enables semantic highlighting for all color themes.

**Comment by gaplo917** [comment]
@stanley0010 Thank you.
