### ISSUE TITLE
can't change font size！！！

### ISSUE THREAD

**Issue by perfectGay** [gaplo917/GapStyle#41]
![image](https://user-images.githubusercontent.com/54127694/175847416-8894a0eb-e28f-4d6b-9da5-e356bf9701a4.png)

**Comment by perfectGay** [comment]
![image](https://user-images.githubusercontent.com/54127694/175847463-0c6ec148-2822-4e4e-b32a-7f3ebb74fc7e.png)

**Comment by gaplo917** [comment]
@perfectGay 

Hi, please  click this to change

![image](https://user-images.githubusercontent.com/5468398/175848106-5e4c1f9a-6dd8-4e9b-8403-79f46efbe89e.png)
