### ISSUE TITLE
Support for latest Intellij?

### ISSUE THREAD

**Issue by JimSR** [gaplo917/GapStyle#46]
Hey, I have been using this theme for years. However with the new UI changes in Intellij IDEA it is no longer supported it seems.

**Comment by gaplo917** [comment]
let me check on it.

**Comment by JimSR** [comment]
Tried to get it to work with the classic UI plugin, but also no luck there.

**Comment by JimSR** [comment]
@gaplo917 Any update from your side?

**Comment by gaplo917** [comment]
@JimSR Thank you for the reminder. I am sorry I found no issues last few weeks and forgot to reply this thread. Please check the following to see if it's applicable to you. If not, could you briefly explain which scenarios don't work and provide some screenshots for me?

Environment: Mac 14.6.1 and latest IntelliJ IDEA Ultimate 2024.2.2

1. uninstalled the plugin.
2. search on Marketplace and install GapStyle again.

<img width="979" alt="Screenshot 2024-09-24 at 8 59 42 AM" src="https://github.com/user-attachments/assets/8417dda4-6948-411d-89e5-e2a56d39d580">

<img width="1227" alt="Screenshot 2024-09-24 at 9 06 31 AM" src="https://github.com/user-attachments/assets/171c80d3-2490-4840-abf5-e9f7d6ac3b97">


<img width="408" alt="Screenshot 2024-09-24 at 9 06 17 AM" src="https://github.com/user-attachments/assets/8e218314-de6d-4358-afdc-388b94995f32">

⚠️⚠️⚠️
> Note: Some compiled languages like Kotlin/Java required you setup proper JDK, setup sources folder, and might also required sucessful sync of Gradle or Maven in order to show the syntax highlight.

### Highlighting not yet work (intelliJ beahviour)
<img width="1395" alt="Screenshot 2024-09-24 at 9 14 08 AM" src="https://github.com/user-attachments/assets/b376848f-0866-4d6f-b7e9-88508119c0a5">

### Setup sources folder
<img width="1394" alt="Screenshot 2024-09-24 at 9 15 09 AM" src="https://github.com/user-attachments/assets/7650855f-762d-4723-a481-3a480751afa4">

### Working
<img width="1392" alt="Screenshot 2024-09-24 at 9 15 17 AM" src="https://github.com/user-attachments/assets/a32afe0c-d85b-4186-a4d0-8b9d707052c6">
