### ISSUE TITLE
2018.3.x issues

### ISSUE THREAD

**Issue by gaplo917** [gaplo917/GapStyle#6]
* [x] bottom line is too light #5 
* [x] CFML attribute name should sync with HTML
* [x] CoffeeScript function name should use Monokai green
* [x] Cucumber Multiline string should use Monokai yellow
* [x] Add Ruby support

**Comment by gaplo917** [comment]
#5 work around before next release for: 
Color Scheme > General >  Editor >  Separator line below

untick `Foreground`

<img width="1154" alt="screenshot 2018-12-10 at 11 54 18 am" src="https://user-images.githubusercontent.com/5468398/49710078-5c4fb900-fc72-11e8-957e-967e0a1b8491.png">

**Comment by doforward** [comment]
thanks, it's working...

**Comment by doforward** [comment]
> #5 work around before next release for:
> Color Scheme > General > Editor > Separator line below
> 
> untick `Foreground`
> 
> <img alt="screenshot 2018-12-10 at 11 54 18 am" width="1154" src="https://user-images.githubusercontent.com/5468398/49710078-5c4fb900-fc72-11e8-957e-967e0a1b8491.png">

thanks,it's working...
