### ISSUE TITLE
DataGrip support

### ISSUE THREAD

**Issue by Acris** [gaplo917/GapStyle#8]
Hi,
I very love this color scheme and thank you for this awesome work. Can you add DataGrip support for this plugin?
Thank you very much!

**Comment by gaplo917** [comment]
Thanks! I have to double check the compatibility on the DataGrip IDE to see if any language style is syntax highlighted nicely.

In the mean time, you can manually import the .jar into DataGrip IDE 👍🏻

You can find the .jar file in release section.

**Comment by gaplo917** [comment]
@Acris supported

**Comment by Acris** [comment]
Thank you very much!
